name: Fork Tests

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]

jobs:
  build:
    if: github.repository_owner != 'adobe'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install
      working-directory: test
    - run: npm run lint
    - run: npm test
      working-directory: test
      env:
        CI: true
